// This file is generated by Cogent

#ifndef CAN_FRAME_0_H__
#define CAN_FRAME_0_H__

#include <cogent-defns.h>

enum {
    LET_TRUE = 1,
} ;
enum {
    LETBANG_TRUE = 1,
} ;
enum untyped_func_enum {
    FUN_ENUM_get_sid_eid,
} ;
typedef enum untyped_func_enum untyped_func_enum;
typedef untyped_func_enum t8;
#define FUN_DISP_MACRO_dispatch_t8(a1, a2, a3)\
{\
    {\
        a1 = get_sid_eid(a3);\
    }\
}
struct t1 {
    unsigned int data[4U];
} ;
typedef struct t1 t1;
struct t2 {
    SArr *data;
    u8 dlc;
    t1 *ident;
    u8 prio;
} ;
typedef struct t2 t2;
struct t7 {
    u32 p1;
    u32 p2;
} ;
typedef struct t7 t7;
static inline t7 get_sid_eid(t2 *);
static inline t7 dispatch_t8(untyped_func_enum a2, t2 *a3)
{
    return get_sid_eid(a3);
}
typedef t2 CanFrame;
typedef t1 CanId;
typedef t2 *get_sid_eid_arg;
typedef t7 get_sid_eid_ret;
#endif


