// This file is generated by Cogent

#include "can_frame_0.h"

static inline unsigned int d4_get_eff_part0(t1 *b)
{
    return (*b).data[1U] >> 0U & 4294967295U;
}
static inline u32 d3_get_eff(t1 *b)
{
    return (u32) d4_get_eff_part0(b) << 0U;
}
static inline unsigned int d6_get_id_part0(t1 *b)
{
    return (*b).data[0U] >> 0U & 4294967295U;
}
static inline u32 d5_get_id(t1 *b)
{
    return (u32) d6_get_id_part0(b) << 0U;
}
static inline t7 get_sid_eid(t2 *a1)
{
    t2 *r2 = a1;
    t1 *r3 = (*r2).ident;
    u32 r4 = d3_get_eff(r3);
    t1 *r5 = (*r2).ident;
    u32 r6 = d5_get_id(r5);
    u32 r7 = 0U;
    bool_t r8 = (bool_t) {.boolean = r4 != r7};
    t7 r9;
    
    if (r8.boolean) {
        u32 r10 = 18U;
        u32 r11 = r10 >= 32U ? 0U : r6 >> r10;
        u32 r12 = 262143U;
        u32 r13 = r6 & r12;
        
        r9 = (t7) {.p1 = r11, .p2 = r13};
    } else {
        u32 r14 = 0U;
        
        r9 = (t7) {.p1 = r6, .p2 = r14};
    }
    
    t7 r15 = r9;
    
    return r15;
}


