#!/bin/bash
#
#
# Copyright 2014, NICTA
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(NICTA_BSD)
#

# Fetch directory this script is stored in.
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Add repo version of Isabelle to our path.
export PATH="${DIR}/isabelle/bin:$PATH"

# Set up environment variables
export AC_DIR=$DIR/autocorres-1.6.1


# Run the tests from the script directory.
cd ${DIR}
python3 ./regression/run_tests.py "$@" -x autocorres-1.6.1 -x isabelle -x c-refinement --limit 50
