/*
This file is generated by Cogent

*/

typedef void *SysState;
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;
typedef unsigned long long u64;
typedef struct unit_t {
            int dummy;
        } unit_t;
typedef struct bool_t {
            u8 boolean;
        } bool_t;
enum {
    LET_TRUE = 1,
} ;
enum {
    LETBANG_TRUE = 1,
} ;
enum untyped_func_enum {
    FUN_ENUM_wordarray_put2_0,
    FUN_ENUM_wordarray_put2_u32,
} ;
typedef enum untyped_func_enum untyped_func_enum;
typedef untyped_func_enum t2;
typedef struct t1 t1;
struct WordArray_u32 {
    int len;
    u32 *values;
} ;
typedef struct WordArray_u32 WordArray_u32;
struct t1 {
    WordArray_u32 *arr;
    u32 idx;
    u32 val;
} ;
static inline WordArray_u32 *wordarray_put2_0(t1);
static inline WordArray_u32 *wordarray_put2_u32(t1);
static inline WordArray_u32 *dispatch_t2(untyped_func_enum a2, t1 a3)
{
    switch (a2) {
        
      case FUN_ENUM_wordarray_put2_0:
        return wordarray_put2_0(a3);
        
      default:
        return wordarray_put2_u32(a3);
    }
}
typedef u32 ErrCode;
typedef u32 WordArrayIndex;
typedef t1 wordarray_put2_0_arg;
typedef WordArray_u32 *wordarray_put2_0_ret;
typedef t1 wordarray_put2_u32_arg;
typedef WordArray_u32 *wordarray_put2_u32_ret;
static inline WordArray_u32 *wordarray_put2_u32(t1 a1)
{
    t1 r2 = a1;
    WordArray_u32 *r3 = wordarray_put2_0(r2);
    
    return r3;
}
u16 u8_to_u16(u8 x)
{
    return (u16) x;
}
u32 u8_to_u32(u8 x)
{
    return (u32) x;
}
u64 u8_to_u64(u8 x)
{
    return (u64) x;
}
u8 u16_to_u8(u16 x)
{
    return (u8) x;
}
u32 u16_to_u32(u16 x)
{
    return (u32) x;
}
u8 u32_to_u8(u32 x)
{
    return (u8) x;
}
u16 u32_to_u16(u32 x)
{
    return (u16) x;
}
u64 u32_to_u64(u32 x)
{
    return (u64) x;
}
u32 u64_to_u32(u64 x)
{
    return (u32) x;
}
u8 u64_to_u8(u64 x)
{
    return (u8) x;
}
u16 u64_to_u16(u64 x)
{
    return (u16) x;
}
WordArray_u32 *wordarray_put2_0(t1 args)
{
    if (__builtin_expect(!!(args.idx < args.arr->len), 1))
        args.arr->values[args.idx] = args.val;
    return args.arr;
}


