(*
This file is generated by Cogent

*)

theory Fail_div_by_zero_Deep_Desugar
imports "Cogent.Cogent"
begin

lemmas abbreviated_type_defs =
  TrueI

ML \<open>
val Cogent_functions = []
val Cogent_abstract_functions = []
\<close>

end
