name:                minigent
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018-2019 Data61; Commonwealth Science and Research Organisation (CSIRO) ABN 41 687 119 230"

extra-source-files: []

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A miniature implementation of a miniature Cogent.

dependencies:
- base >= 4.7 && < 5
- Earley >= 0.12.1
- containers
- transformers
- mtl
- text
- prettyprinter
- directory
- filepath
- prettyprinter-ansi-terminal
- matrix
- vector

library:
  source-dirs: src

executables:
  minigent-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - minigent

tests:
  minigent-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - minigent
    - smallcheck
    - system-posix-redirect
    - bytestring
    - ansi-terminal
