#
# Copyright 2016, NICTA
#
# This software may be distributed and modified according to the terms of
# the GNU General Public License version 2. Note that NO WARRANTY is provided.
# See "LICENSE_GPLv2.txt" for details.
#
# @TAG(NICTA_GPL)
#

SRC=fsop.cogent

DSL=cogent

all:
	$(DSL) -t $(SRC)
tc:
	$(DSL) -t $(SRC)
pretty:
	$(DSL) -p $(SRC)
clean:
	rm -f $(SRCP)

re: clean all
	@echo -n
